### ISSUE TITLE
Узнать имя текущего модуля?

### ISSUE THREAD

**Issue by alglyzin** [itlessons/php-routing#2]
$router -> add('form_name', '/form/(name:any)', 'forms:index', 'POST');

Если мы на странице example.ru/form, то нужно получить имя -> "form_name"

Как это сделать?

**Comment by itlessons** [comment]
В текущей реализации никак. Так как UrlMatcher не обладает именами роутов. Но реализовать эту возможность можно. 

Надо расширить метод UrlMatcher->register. Передав последним параметром имя. И в методе UrlMatcher->match задать свойство классу Route (свойство надо реализовать).

Неуверен, нужна ли такая возможность в текущей реализации.

Извините за долгий ответ. Отпуск.

**Comment by alglyzin** [comment]
Можете реализовать?

**Comment by itlessons** [comment]
Не вижу в этом смысла, так как это усложнит понимание кода, который в первую очередь создан для обучения. К тому же не могу представить реальных задач, в которых бы понадобилось бы определить имя роута. Ну разве что для дебага. Но тут хватит и имени контроллера. По задумке имя нужно только для генерации ссылок.
